apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-rabbitmq
  name: ms-rabbitmq
spec:
  type: NodePort
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
    - name: "8080"
      port: 8080
      targetPort: 15672
  selector:
    app: ms-rabbitmq
status:
  loadBalancer: {}
